site_name: Cours d'initiation à l'algorithmie
nav:
    - Accueil & Déroulement des séances: README.md
    - 1 - Architecture logicielle: 1_Architecture_logicielle.md
    - 2 - Validité Logiciel Numérique: 2_Validite_logiciel_numerique.md
    - 3 - Algorithmie:
        - "Introduction à l'algorithmie": 3_Algorithmie.md
        - "Approche 'diviser pour mieux règner'": 3.b_diviser_pour_regner.md
        - "Exercices": 3.c_exercices_algo.md
    - 4 - Introduction à Python:
        - "Introduction à Python": 4_intro_python.md
        - "Exercices": 4.c_exercices_python.md
    - 5 - Introduction à la Théorie des Graphes:
        - "Introduction à la Théorie des Graphes": 5_intro_tdg.md
        - "Exercices": 5.c_exercices_tdg.md
        - "Cours détaillé (pdf)": 5.b_Cours_tdg.pdf
    - Exercices:
        - "Exercices d'Algorithmie": 3.c_exercices_algo.md
        - "Exercices de Python": 4.c_exercices_python.md
        - "Exercices de Théorie des Graphes": 5.c_exercices_tdg.md
    - TODO:
        - "Liste des Tâches": todo.md
markdown_extensions:
    - attr_list
    - pymdownx.emoji:
        emoji_index: !!python/name:material.extensions.emoji.twemoji
        emoji_generator: !!python/name:material.extensions.emoji.to_svg
    - fenced_code
    - toc:
        baselevel: 2
    - pymdownx.highlight:
        anchor_linenums: true
        line_spans: __span
        pygments_lang_class: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences
theme:
  name: material
  language: fr
  palette:
    primary: blue grey
    accent: deep purple
  logo: logo.svg
  features:
    - content.code.copy
